### ISSUE TITLE
Two typos in "1. Indexing (Or Lack Thereof)"

### ISSUE THREAD

**Issue by SeongWang-PD** [kevinheavey/modern-polars#28]
1.3 [Indexing](https://kevinheavey.github.io/modern-polars/indexing.html#indexing) section, first sentence states ["do to"](https://kevinheavey.github.io/modern-polars/indexing.html#indexing:~:text=always%20forgets%20how-,do%20to,-anything%20non%2Dtrivial) rather than "to do"

1.5 [SettingWithCopy](https://kevinheavey.github.io/modern-polars/indexing.html#settingwithcopy) section, fourth sentence states ["attact"](https://kevinheavey.github.io/modern-polars/indexing.html#settingwithcopy:~:text=popular%20enough%20to-,attact,-the%20same%20crowd) rather than "attract."

**Comment by kevinheavey** [comment]
Thanks, fixed
