### ISSUE TITLE
Predicate pushdown link broken

### ISSUE THREAD

**Issue by rogerjbos** [kevinheavey/modern-polars#29]
[predicate pushdown](https://pola-rs.github.io/polars-book/user-guide/optimizations/lazy/predicate-pushdown.html) link is not working on [this](https://kevinheavey.github.io/modern-polars/scaling.html#:~:text=Polars%20can%20handle%20some%20larger,in%20a%20lot%20of%20data.) page.

Any why do these examples usually only show python examples.  Rust users needs examples too (at least I do).

**Comment by kevinheavey** [comment]
Thanks, fixed
